# Generated by Django 5.2.7 on 2025-11-03 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('ingredients', models.TextField(help_text='Ingresa los ingredientes, uno por línea o separados por comas', verbose_name='Ingredientes')),
                ('instructions', models.TextField(help_text='Describe paso a paso cómo preparar la receta', verbose_name='Instrucciones')),
                ('preparation_time', models.PositiveIntegerField(default=30, help_text='Tiempo en minutos', verbose_name='Tiempo de preparación')),
                ('cooking_time', models.PositiveIntegerField(default=0, help_text='Tiempo en minutos', verbose_name='Tiempo de cocción')),
                ('servings', models.PositiveIntegerField(default=4, verbose_name='Porciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-created_at'],
            },
        ),
    ]
