# Generated by Django 5.2.7 on 2025-11-04 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at'], 'verbose_name': 'recipe', 'verbose_name_plural': 'recipes'},
        ),
    ]
